### ISSUE TITLE
Conversion doesn't work

### ISSUE THREAD

**Issue by Accoast** [aloussase/AlexandriaApp#27]
Tried a convert books from EPUB to PDF. Does not work. Tried 3 different one, all of them did fail.
Successfuly converted a PDF into EPUB though. Seems to be only the issue with EPUB into PDF conversion. Can't attach screenshot here, it just says: "There was an error while converting this book."

**Comment by aloussase** [comment]
It should be fixed now, try again or if that doesn't work try in one hour approximately.
